name: r_username
description: A library for generating username. r_username is  inspired by the Python package.
version: 0.0.1
homepage: "https://github.com/NazeemNato/r_username"

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter