name: r_username
description: Username generator
version: 0.0.1
author: Muhammed Nazeem
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter